services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password_mysql_kamu
      MYSQL_DATABASE: puskesmas_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      # Perhatikan bahwa host sekarang menunjuk ke nama service 'db'
      - DB_HOST=db 
      - DB_USER=root
      - DB_PASSWORD=password_mysql_kamu
      - DB_NAME=puskesmas_db
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin123
      - JWT_SECRET=rahasia_puskesmas_super_aman
      # Masukkan kredensial GCP kamu di sini
      - AWS_REGION=asia-southeast2
      - AWS_ACCESS_KEY_ID=kunci_akses_gcp_kamu
      - AWS_SECRET_ACCESS_KEY=kunci_rahasia_gcp_kamu
      - S3_BUCKET_NAME=nama_bucket_puskesmas
      - S3_ENDPOINT=https://storage.googleapis.com
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  db_data: